
spring:
  profiles:
    active: -dev

---

server:
  port: 7001
spring:
  profiles: dev
  application:
    name: cloud-config-eureka-client

eureka:
  instance:
    hostname: 192.168.22.107 #eureka服务端的实例名称
  server:
    enable-self-preservation: false # 设为false，关闭自我保护
    
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://192.168.22.107:20002/eureka/


---

server:
  port: 7001
spring:
  profiles: test
  application:
    name: cloud-config-eureka-client

eureka:
  instance:
    hostname: 192.168.22.107 #eureka服务端的实例名称
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://192.168.22.107:20002/eureka/


