server:
  port: 9527
  
spring:
  application:
    name: cloud-zuul-gateway

eureka:
  client:
    service-url:
      #客户端注册进eureka服务列表内
      defaultZone: http://192.168.22.107:20002/eureka/
  instance:
    #注册到eureka后，status的名字（服务在eureka的唯一标志）
    instance-id: dmsdbj-zuul.com
    #访问路径可以显示IP地址
    prefer-ip-address: true

zuul:    
  routes:
    #个人中心
    personalcenter.path: /personalcenter/**
    personalcenter.serviceId: integral-personalcenter-consumer
    #米圈
    gam.path: /gam/**
    gam.serviceId: integral-gam-consumer
    #鬼市
    ghostmarket.path: /ghostmarket/**
    ghostmarket.serviceId: integral-ghostmarket-consumer
    #知识付费
    knowledgepay.path: /knowledgepay/**
    knowledgepay.serviceId: integral-knowledgepay-consumer
    #米币
    mcoin.path: /mcoin/**
    mcoin.serviceId: integral-mcoin-consumer
    #任务管理
    taskmanage.path: /taskmanage/**
    taskmanage.serviceId: integral-taskmanage-consumer
  #使真实服务地址不可用（忽略单个）
#  ignored-services: spring-cloud-provider-dept
  #忽略所有
  ignored-services: "*"
  #前缀
  prefix: /integral
  

info:
  app.name: cloud-zuul-9527
  company.name: www.dmsdbj.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

